### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by mase76** [PrivacyApps/document-viewer#112] opened 2015-06-15 15:14 UTC
Please add printing support over Android's printing subsystem.

**Comment by frazzmark** [comment] 2015-06-15 17:47
:+1:

**Comment by KrasnayaPloshchad** [comment] 2016-04-13 06:55
That would be useful if some people want to print via certain ways as ePrint.

**Comment by Dionis0s** [comment] 2017-11-30 18:26
I want to push this feature! It would be nice!!

**Comment by DJCrashdummy** [comment] 2017-12-30 16:57
i guess this can be closed as it is a duplicate of #146.

**Closed** 2017-12-30 19:11 UTC
Labels: enhancement
